name: pull request check workflow
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  pull_request:
    branches:
      - master
jobs:
        build:
                runs-on: ubuntu-latest
                steps:
                        - name: checkout repository
                          uses: actions/checkout@v2
                        - name: Set up JDK 1.8
                          uses: action/setup-java@v1
                          with:
                                  java-version: 1.8
                        - name: Build with Gradle
                          run: ./gradlew build
